name: ⚙️ Custom Issue
about: Submit a custom issue or suggestion that doesn’t fit into other categories
title: "[CUSTOM] "
labels: ["custom"]
assignees: []

---

### 🔍 Have You Searched Existing Issues?

- [ ] I have searched the existing issues to avoid duplicates

---

### 📝 Issue Summary  
Provide a short summary of the custom issue.  
_Example: Enhancement suggestion for the search functionality._

---

### 🔍 Issue Description  
Describe the issue or suggestion in detail.  
Include any relevant context, use case, or scenario where this issue occurs or is important.

---

### 💡 Proposed Solution (Optional)  
If you have any ideas or suggestions for solving this issue, describe them here.

### 📂 Category  
_Select the category that best describes the issue:_

- [ ] Enhancement  
- [ ] Refactor  
- [ ] Security  
- [ ] Design  
- [ ] Other  

---

### 📘 Additional Context (Optional)  
Add any other context, links, screenshots, or information that might be relevant.

---

### 🙌 Contributor Checklist (Optional)

- [ ] I have searched existing issues to avoid duplicates  
- [ ] I agree to follow this project's Code of Conduct  
- [ ] I am a GSSOC'25 contributor  
- [ ] I want to work on this issue  
